# Generated by Django 5.0.1 on 2024-03-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emails',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
