# Generated by Django 5.0.1 on 2024-03-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='options',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=20, null=True),
        ),
    ]
